services:
  - type: web
    name: bootchat2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        fromDatabase:
          name: bootchat2-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: bootchat2-db
    plan: free